### ISSUE TITLE
Deployment failed in south east asia

### ISSUE THREAD

**Issue by fabianjogschies** [Azure/data-management-zone#116]
correlation id: f874e407-556b-44d6-8af0-a5409fb27f70

![image](https://user-images.githubusercontent.com/6885215/127498751-39060acd-35a5-4799-b4fa-88413f8ea03a.png)

error regarding purview deployment, no more purview instances allowed:

`{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidTemplateDeployment\",\r\n    \"message\": \"The template deployment 'purview001' is not valid according to the validation procedure. The tracking id is 'c307c7c9-4e94-4d31-8c13-90179a34698a'. See inner errors for details.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"2005\",\r\n        \"message\": \"Tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 with 100 accounts has surpassed its resource quota for southeastasia location. Please try creating in other available locations or contact support.\"\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}`

Region: South East Asia

**Comment by marvinbuss** [comment]
Thanks @fabianjogschies! This is something which is sadly not in our hands. The tenant has reached the soft limit of 100 Purview instances. This can be increased by opening a support ticket, but this is not something we can change on our side. We have seen this issue before and I will add this to the list of known issues. Would this be ok?

**Comment by fabianjogschies** [comment]
Yes i'm also aware of this it happenend also in west europe as purview was released. 
If this can be helpful i can make contact to the pg an raise the issue again as i see that this will be likely to be an increasing bug if we roll out esa broadly.
Just let me know

**Comment by marvinbuss** [comment]
Feel free to open another ticket or reach out to the Purview team.
Most customers will probably not hit that issue as they do not have 100s of purview instances in their tenant. But this will become an issue, once we want to onboard more users. Let me also reach out to some contacts.

You will see a PR later today, which will add a section in this doc:  https://github.com/Azure/data-management-zone/blob/main/docs/EnterpriseScaleAnalytics-KnownIssues.md
