### ISSUE TITLE
Deployment failed in west europe

### ISSUE THREAD

**Issue by rokahr** [Azure/data-management-zone#117]
The deployment of the dataManagement zone was successful, but not the one for the dataLandingZone.
Correlation ID: f953f92e-3406-4414-99c2-bec526a01554

**Comment by rokahr** [comment]
![image](https://user-images.githubusercontent.com/13717324/127501186-cc31cd27-afda-42b6-a67d-be4ab0645004.png)

**Comment by marvinbuss** [comment]
Thanks @rokahr. Let me look into this.

**Comment by marvinbuss** [comment]
This was tested again and did not fail. Seems like an RP issue. We will keep an eye on it and reopen, if this occurs again.
