### ISSUE TITLE
Add Note About Global Uniqueness of Prefix in Azure Template

### ISSUE THREAD

**Issue by AnalyticJeremy** [Azure/data-management-zone#125]
When using the "Deploy to Azure" button, the custom template asks for a "Data Management Zone Prefix" in the second step.  In the description of the field or in the info tooltip, it might be helpful to mention that this prefix should be globally unique.

In the workshops we have run, one of the common errors that users encounter is that they try to use a very common prefix like `dmz` or `dataman`.  I know we don't have a way for the UI to check for global uniqueness, but if we put a note on the screen, it might prompt the user to think a little harder about the prefix they select.  This could help prevent a very common issue.

**Comment by marvinbuss** [comment]
Let me also evaluate whether we can add some checks for some resources.

**Comment by marvinbuss** [comment]
I will add name checks to the portal experiences to check for name availability before a deployment is submitted.
