### ISSUE TITLE
Cannot Run a Second Deployment

### ISSUE THREAD

**Issue by AnalyticJeremy** [Azure/data-management-zone#127]
**Describe the bug**
I used the "Deploy to Azure" button to deploy the ["Enterprise-Scale Analytics" template](https://raw.githubusercontent.com/Azure/data-management-zone/main/docs/reference/portal.enterpriseScaleAnalytics.json).  My first deployment ran successfully.  I wanted to run the template again, but I couldn't because the deployment name `dataManagementZoneDeployment` was already in use.

Can we add a random string to the end of the deployment name so the names are unique?

**Steps to reproduce**
1.  Use the `portal.enterpriseScaleAnalytics.json` template to run a deployment
2.  Use the same template again to create a second deployment
3.  Get validation error

**Error message**
```json
{"code":"InvalidDeploymentLocation","message":"Invalid deployment location 'eastus2'. The deployment 'dataManagementZoneDeployment' already exists in location 'centralus'."}
```

**Screenshots**
<img width="957" alt="duplicate-deployment-name-error" src="https://user-images.githubusercontent.com/4240319/127527194-b4c705f9-90a4-4d02-8602-2e893af02bfd.png">

**Comment by marvinbuss** [comment]
Thanks @AnalyticJeremy for catching this. So this is what you tried to do:
![image](https://user-images.githubusercontent.com/34542414/127647874-37a06283-bedd-46d8-8403-cc983b9f2676.png)
?

I will add a prefix.

**Comment by marvinbuss** [comment]
I will implement the fix that I mentioned above today.

**Comment by marvinbuss** [comment]
One more change required to fix this.
