### ISSUE TITLE
Template Is Invalid When Applying Tags

### ISSUE THREAD

**Issue by AnalyticJeremy** [Azure/data-management-zone#130]
**Describe the bug**
I used the "Deploy to Azure" button to deploy the ["Enterprise-Scale Analytics" template](https://raw.githubusercontent.com/Azure/data-management-zone/main/docs/reference/portal.enterpriseScaleAnalytics.json).  On the fourth step, I tried to add tags to my deployment.  When I clicked the "Create" button, I received a template validation error.

When I removed my tags, the process ran correctly.

**Steps to reproduce**
1.  Use the `portal.enterpriseScaleAnalytics.json` template
2.  Add tags to the deployment
3.  Get validation error when creating the resources

**Error message**
```json
{"code":"InvalidTemplate","message":"Deployment template parse failed: 'Error reading string. Unexpected token: StartObject. Path 'EnterpriseScaleAnalytics'.'."}
```

**Screenshots**
<img width="963" alt="esa-tag-error" src="https://user-images.githubusercontent.com/4240319/127529401-7cc9ecb3-6eb5-49fe-aa91-d585474d6835.png">

**Comment by marvinbuss** [comment]
Good catch. Let me fix this tomorrow morning! 👍

**Comment by marvinbuss** [comment]
Took me a while to get the filtering right. This will be fixed in the next release. Thanks for submitting this!
