### ISSUE TITLE
Deploy Rules to Azure Firewall Policy error

### ISSUE THREAD

**Issue by abdale** [Azure/data-management-zone#144]
I'm seeing this error when I try to deploy into a Enterprise-scale environment:

![image](https://user-images.githubusercontent.com/8771696/129102371-8cf6e0e7-e66b-4556-8ea4-fedee0fb773b.png)
```
{
  "code": "SubscriptionNotFound",
  "message": "The subscription 'grp-azfwpolicy-eastus2' could not be found."
}
```
Screenshot of the configuration:

![image](https://user-images.githubusercontent.com/8771696/129102521-7aa99024-5906-4c1f-83ba-a091f48c0308.png)

**Comment by marvinbuss** [comment]
Thanks @abdale . I already discovered the big and will fix it in the next few days or ehen I am back from vacation. Sorry for the delay.

**Comment by abdale** [comment]
> Thanks @abdale . I already discovered the big and will fix it in the next few days or ehen I am back from vacation. Sorry for the delay.

Thanks - Let's look at it when you're back!
