### ISSUE TITLE
Error for nonexistent firewall?

### ISSUE THREAD

**Issue by abdale** [Azure/data-management-zone#146]
Not urgent. Logging this for post-vacation analysis, @marvinbuss 

![image](https://user-images.githubusercontent.com/8771696/129282958-bb1bf292-8f4a-4c55-a55e-078f854bc191.png)

Since when you select the above option, it uses the existing firewall and does not create a new one, but throws an error after deployment (dependency issue?).

![image](https://user-images.githubusercontent.com/8771696/129283069-63f011be-3bde-4707-a1df-70c3184e3cd5.png)

**Comment by marvinbuss** [comment]
@abdale Is this PR the fix for this bug: https://github.com/Azure/data-management-zone/pull/145 ?

**Comment by abdale** [comment]
No, this is unrelated to #145.
