### ISSUE TITLE
Feature Request : Provisioning a Jump Box within Data Landing Shared Product Virtual Network

### ISSUE THREAD

**Issue by aaliraaza** [Azure/data-management-zone#155]
**It will be really useful and productive to have a pre-provisioned Jump Box within Data Landing Shared Product Virtual Network for quicker adoption and get cracking straightaway with any labs / workshops or Demo purposes.**

**Comment by marvinbuss** [comment]
@aaliraaza Can you please provide feedback whether the doc written here helps when connecting to the environment:
https://github.com/Azure/data-management-zone/blob/feature/bastion-host/docs/guidance/EnterpriseScaleAnalytics-ConnectToEnvironmentsPrivately.md

FYI: @denniseik
