### ISSUE TITLE
Bug Report: supported regions list outdated

### ISSUE THREAD

**Issue by mariekekortsmit** [Azure/data-management-zone#226]
It seems like the officially supported deployment regions:
- (Asia Pacific) Japan East
- (Europe) France Central
- (Europe) Germany West Central
- (US) Central US

are not an option as Azure Purview is not available in those. Or am I missing something here?

**Comment by marvinbuss** [comment]
Hi @mariekekortsmit,
Thanks for submitting the issue. Just as mentioned by @sasever in this thread https://github.com/Azure/data-landing-zone/issues/208 we do nt want to limit the user too much wrt where Enterprise-Scale Analytics is available. Therefore, we are deploying the Purview by default in North Europe as you can see here: https://github.com/Azure/data-management-zone/blob/718dd5f81e7410f0df2f8513cefa8dcf453f9332/infra/modules/services/purview.bicep#L24-L54

**Comment by mariekekortsmit** [comment]
Thanks for the background info! Makes sense to me :)
