### ISSUE TITLE
Azure CLI version 2.29.1 breaks deployment

### ISSUE THREAD

**Issue by abdale** [Azure/data-management-zone#227]
![image](https://user-images.githubusercontent.com/8771696/141153123-73d5d659-a852-40a3-bd43-84faa92f8951.png)

Changing it to the latest version (2.30.0) fixed it.

cc @AnalyticJeremy

**Comment by AnalyticJeremy** [comment]
Here's what I think happened:  Last week, the login container and the CLI container were out-of-sync on their versions.  This broke the functionality.  @marvinbuss correctly pinned the CLI container to a previous version so it would match the login container.  Now, however, the login container has caught up... so we need to go back to "latest" on the CLI container.

**Comment by marvinbuss** [comment]
Thanks @AnalyticJeremy and @abdale. It was actually the mismatch between the CLI Action and the Azure CLI version installed on the agent causing the issue 1-2 weeks ago. The team is working on a permanent fix, but let me fix this asap.

**Comment by marvinbuss** [comment]
PR is open and will be merged soon. Thanks for reporting the bug!
