### ISSUE TITLE
Error when trying to deploy

### ISSUE THREAD

**Issue by devlace** [Azure/data-management-zone#229]
**Describe the bug**
While deploying using the Deploy to Azure button, I ran into the following error when deploying the **Data Landing Zone** part. The Data Management Zone deployed successfully.

![image](https://user-images.githubusercontent.com/5771063/141250778-1473c505-960a-4d90-b1be-f3fb85328fb3.png)

Error:
```
"Deployment template validation failed: 'The template parameters 'purviewRootCollectionAdminObjectIds' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'location, environment, prefix, tags, vnetAddressPrefix, servicesSubnetAddressPrefix, databricksIntegrationPublicSubnetAddressPrefix, databricksIntegrationPrivateSubnetAddressPrefix, databricksProductPublicSubnetAddressPrefix, databricksProductPrivateSubnetAddressPrefix, powerBiGatewaySubnetAddressPrefix, dataIntegration001SubnetAddressPrefix, dataIntegration002SubnetAddressPrefix, dataProduct001SubnetAddressPrefix, dataProduct002SubnetAddressPrefix, dataManagementZoneVnetId, firewallPrivateIp, dnsServerAdresses, administratorPassword, purviewId, purviewManagedStorageId, purviewManagedEventHubId, purviewSelfHostedIntegrationRuntimeAuthKey, deploySelfHostedIntegrationRuntimes, portalDeployment, privateDnsZoneIdKeyVault, privateDnsZoneIdDataFactory, privateDnsZoneIdDataFactoryPortal, privateDnsZoneIdBlob, privateDnsZoneIdDfs, privateDnsZoneIdSqlServer, privateDnsZoneIdMySqlServer, privateDnsZoneIdEventhubNamespace, privateDnsZoneIdSynapseDev, privateDnsZoneIdSynapseSql'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.",
```

**Steps to reproduce**

1.  Navigate to https://github.com/Azure/data-management-zone, and click on the first Deploy to Azure button in the table.
![image](https://user-images.githubusercontent.com/5771063/141250312-0efe696e-3c74-4f68-9e88-7137f26e4aae.png)

2.  Fill in fields as follows (Data Landing Zone)
![image](https://user-images.githubusercontent.com/5771063/141250620-06c7bb49-c912-4732-96aa-1a9ab318ab3d.png)

**Screenshots**

**Comment by marvinbuss** [comment]
Thanks @devlace for reporting this. The PR is already open and will be merged soon to fix the bug. Sorry for the inconveniences caused!
