### ISSUE TITLE
DMA Set up in Central India

### ISSUE THREAD

**Issue by namrata01Apr** [Azure/data-management-zone#256]
As part of a customer request need the DMA templates for Central India.

**Comment by marvinbuss** [comment]
Hi @amanjeetsingh,
Can we check whether this is possible as part of the ongoing work here: https://github.com/Azure/data-management-zone/pull/194 ?

**Comment by marvinbuss** [comment]
@namrata01Apr I opened some PRs and reached out to the team directly to make the templates available in the requested regions. Thanks for the Issue! 👍

**Comment by namrata01Apr** [comment]
Thank you so much Marvin for the super quick response and action on this .
