### ISSUE TITLE
Feature: Standard instead of Premium SKU of Firewall

### ISSUE THREAD

**Issue by fmms** [Azure/data-management-zone#262]
### Feature or Idea - What?

- Use standard instead of premium firewall (see https://github.com/Azure/data-management-zone/blob/73e450a66062bafb6dc4bf3a1fef24cc4803c319/infra/modules/network.bicep#L160 and https://github.com/Azure/data-management-zone/blob/73e450a66062bafb6dc4bf3a1fef24cc4803c319/infra/modules/network.bicep#L203.
- either switch the default or at least give users the option to configure if there are good reasons 

### Feature or Idea - Why?

- Users evaluating the ESA with no dedicated connectivity subscription most likely focus on the data aspect rather than the firewall
- saving azure consumption for testing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](/CODE_OF_CONDUCT.md)

**Comment by marvinbuss** [comment]
Makes sense. I will provide this option to users after the Christmas break.

**Comment by marvinbuss** [comment]
Please follow the progress of the linked PR.
