### ISSUE TITLE
Feature: Connection to data management landing zone

### ISSUE THREAD

**Issue by miguelperedo** [Azure/data-management-zone#274]
### Feature or Idea - What?

The pipeline that deploys the data management landing zone, should be able to ”pass” the parameters (like: vnet, synapse, id) to the pipeline of the data zone.

### Feature or Idea - Why?

Now we have two repos in DevOps:
One that deploys the data management landing zone, but that has no connection to the data landinzone.
There should be an automated way to ”pass” the output parameters of the data management landing zone to the data landing zone.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Azure/data-management-zone/blob/main/CODE_OF_CONDUCT.md)

**Comment by marvinbuss** [comment]
Same as https://github.com/Azure/data-landing-zone/issues/228

Let's continue the discussion here please: https://github.com/Azure/data-landing-zone/discussions/229
