### ISSUE TITLE
Feature: Naming of the resources groups to follow CAF

### ISSUE THREAD

**Issue by MiguelElGallo** [Azure/data-management-zone#285]
### Feature or Idea - What?

In this [link ] (https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming#example-names-general) from CAF the suggestion for naming resources group is:

rg-<app or service name>-<subscription type>-<###>
Example:
rg-ad-dir-services-shared-001

We have only now the parameter prefix, we cannot achieve that suggested naming convention.

Can this be changed in way that we have a new parameter, for sequential name ### and that resource groups are created following the ACF recommendation
rg-<app or service name>-<subscription type>-<###>

### Feature or Idea - Why?

To comply and follow CAF  suggested best practices.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Azure/data-management-zone/blob/main/CODE_OF_CONDUCT.md)

**Comment by marvinbuss** [comment]
Hi @MiguelElGallo,
Please find our responses for this ask here: https://github.com/Azure/data-management-zone/discussions/188
Please let me know, whether we can close this.

**Comment by marvinbuss** [comment]
Will close this since there has been no response for more than 2 weeks. Please reopen, if you have additional questions.
