### ISSUE TITLE
Bug: Warning Github Actions Node.js 12 deprecation

### ISSUE THREAD

**Issue by vanwinkelseppe** [Azure/data-management-zone#309]
### Deployment Mode

GitHub Actions

### Steps to reproduce

Deploy the resource to GitHub throws deprecation warning for node.js 12.

### Error Message

```json
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

### Screenshots

![image](https://user-images.githubusercontent.com/9077926/214070558-5485e327-a62a-4fa6-bb81-cb468695e4fc.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Azure/data-management-zone/blob/main/CODE_OF_CONDUCT.md)

**Comment by marvinbuss** [comment]
Closed by PRs.
