### ISSUE TITLE
Variable Names in "Update Parameters" Process Refer to DLZ

### ISSUE THREAD

**Issue by AnalyticJeremy** [Azure/data-management-zone#39]
**Describe the bug**
In the "Update Parameters" process, many of the script input parameters and variables have names that refer to a Data Landing Zone when they actually control the Data Management Zone that is being created.

**Comment by marvinbuss** [comment]
This is the same for all repos. This script does not really get exposed to users and they are not really using this scripts elsewhere. For maintennace resons, I would like to use keep the same script across all repos. Changing this can make things more confusing and therefore can make things more error prone.
