### ISSUE TITLE
Randomize key vault resource names

### ISSUE THREAD

**Issue by zeinab-mk** [Azure/data-management-zone#73]
Given the fact that when Key Vault resources are deleted, they are retained for x amount of days because of soft-delete capability in the product, you cannot remove the existing deployment and create new resources with the same name until the soft-delete period. Please consider randomizing the resources names so customers can redeploy the environment if they ever need to start over again.

**Comment by marvinbuss** [comment]
I am closing this for now as we have moved to a different naming strategy and also allow to use longer prefixes (10 chars). We may also add some name availability checks to the Deploy to Azure experience.
