### ISSUE TITLE
Register Azure Purview Provider

### ISSUE THREAD

**Issue by zeinab-mk** [Azure/data-management-zone#74]
It would be nice if registering required Resource Providers for deploying Azure Purview can be included in the deployment templates:

- Microsoft.Purview
- Microsoft.Storage
- Microsoft.EventHub

note: in case you consider including this feature SPN may require additional role.

**Comment by marvinbuss** [comment]
We have added a Notes section here:
https://github.com/Azure/data-management-zone/blob/main/docs/EnterpriseScaleAnalytics-Prerequisites.md#what-will-be-deployed

Do you believe that users require more guidance?
